import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { useEffect } from "react"; // Importamos useEffect para ejecutar código en el cliente
import { app } from "../lib/firebase"; // Asegúrate de que la ruta sea correcta según tu estructura

// Configuración de fuentes
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata para la página
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout principal de la aplicación
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    // Solo inicializamos Firebase en el lado del cliente
    if (typeof window !== "undefined") {
      console.log("Firebase initialized", app);
    }
  }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
