import type { ReportLabel, ReportLang } from "./types";

/**
 * Textos fijos de la reporteria en los dos idiomas.
 *
 * Los entregables (correo, PDF y Excel) salen en ingles; el castellano existe
 * solo para revisar el contenido internamente. Por eso el idioma es un
 * parametro explicito y no una preferencia del destinatario: nadie externo
 * deberia recibir la version castellana por accidente.
 */
export interface ReportStrings {
  reporting: string;
  serviceReport: string;
  dailyTitle: string;
  totalTitle: string;
  hello: string;
  intro: (date: string) => string;
  bulbsProcessed: string;
  lots: string;
  bins: string;
  lot: string;
  variety: string;
  size: string;
  bulbs: string;
  noData: string;
  noBulbs: string;
  company: string;
  service: string;
  process: string;
  reportDate: string;
  generated: string;
  sizeSource: string;
  sizeSourceDeclared: string;
  sizeSourceMeasured: string;
  lotDetail: string;
  lotTotal: string;
  declaredNote: string;
  measuredNote: string;
  binsNote: string;
  footer: string;
  autoGenerated: string;
  sheetDaily: string;
  sheetTotal: string;
  locale: string;
}

const EN: ReportStrings = {
  reporting: "REPORTING",
  serviceReport: "Service report",
  dailyTitle: "Daily summary",
  totalTitle: "Service total summary",
  hello: "Hello",
  intro: (date) =>
    `Attached is the service report for ${date}. The daily detail and the service total are in the PDF and Excel files.`,
  bulbsProcessed: "bulbs processed",
  lots: "lots",
  bins: "bins",
  lot: "Lot",
  variety: "Variety",
  size: "Size",
  bulbs: "Bulbs",
  noData: "No data for this period",
  noBulbs: "No bulbs were processed during this period.",
  company: "Company",
  service: "Service",
  process: "Process",
  reportDate: "Report date",
  generated: "Generated",
  sizeSource: "Size source",
  sizeSourceDeclared: "Declared at lot closing",
  sizeSourceMeasured: "Measured",
  lotDetail: "Lot detail",
  lotTotal: "Total",
  declaredNote:
    "Sizes are the ranges the operator set when closing the lot on the tablet. % is within the lot.",
  measuredNote: "By measured size. % is within the lot.",
  binsNote: "Bins reflect what was declared at lot closing.",
  footer: "QUALIBLICK - Automatic report",
  autoGenerated: "Automatically generated by QUALIBLICK.",
  sheetDaily: "Daily",
  sheetTotal: "Total",
  locale: "en-US",
};

const ES: ReportStrings = {
  reporting: "REPORTERIA",
  serviceReport: "Resumen de servicio",
  dailyTitle: "Resumen diario",
  totalTitle: "Resumen acumulado del servicio",
  hello: "Hola",
  intro: (date) =>
    `Adjuntamos el reporte del servicio correspondiente al ${date}. El detalle del dia y el acumulado estan en los archivos PDF y Excel.`,
  bulbsProcessed: "bulbos procesados",
  lots: "lotes",
  bins: "bins",
  lot: "Lote",
  variety: "Variedad",
  size: "Calibre",
  bulbs: "Bulbos",
  noData: "Sin datos para el periodo",
  noBulbs: "No se registraron bulbos procesados en este periodo.",
  company: "Empresa",
  service: "Servicio",
  process: "Proceso",
  reportDate: "Fecha reportada",
  generated: "Generado",
  sizeSource: "Origen del calibre",
  sizeSourceDeclared: "Declarado al cierre del lote",
  sizeSourceMeasured: "Medido",
  lotDetail: "Detalle por lote",
  lotTotal: "Total",
  declaredNote:
    "Los calibres son los rangos que la operaria dejo definidos al cerrar el lote en la tablet. El % es dentro del lote.",
  measuredNote: "Por calibre medido. El % es dentro del lote.",
  binsNote: "Los bins reflejan lo declarado al cierre del lote.",
  footer: "QUALIBLICK - Reporte automatico",
  autoGenerated: "Mensaje generado automaticamente por QUALIBLICK.",
  sheetDaily: "Diario",
  sheetTotal: "Acumulado",
  locale: "es-CL",
};

export function strings(lang: ReportLang): ReportStrings {
  return lang === "es" ? ES : EN;
}

export function label(value: ReportLabel, lang: ReportLang): string {
  return lang === "es" ? value.es : value.en;
}
