import {
  Body,
  Column,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Img,
  Preview,
  Row,
  Section,
  Text,
} from "@react-email/components";
import type { ServiceReport } from "@/lib/reporting/types";

interface ServiceReportEmailProps {
  daily: ServiceReport;
  total: ServiceReport;
  recipientName?: string | null;
}

const font = "Arial, Helvetica, sans-serif";

export default function ServiceReportEmail({ daily, total, recipientName }: ServiceReportEmailProps) {
  return (
    <Html>
      <Head />
      <Preview>{`Reporte / Report QUALIBLICK - ${daily.serviceName} - ${daily.reportDate}`}</Preview>
      <Body style={{ backgroundColor: "#F1F5F9", margin: 0, fontFamily: font, color: "#172033" }}>
        <Container style={{ maxWidth: 680, margin: "0 auto", backgroundColor: "#FFFFFF" }}>
          <Section style={{ backgroundColor: "#FFFFFF", padding: "30px 34px 22px", borderBottom: "5px solid #0E7490" }}>
            <Img src="cid:qualiblick-logo" alt="QUALIBLICK" width="190" style={{ display: "block", height: "auto" }} />
            <Text style={{ color: "#0E7490", fontSize: 11, letterSpacing: 2, margin: "14px 0 0" }}>REPORTERIA / REPORTING</Text>
            <Heading style={{ color: "#172033", fontSize: 25, margin: "8px 0 0" }}>Resumen de servicio / Service report</Heading>
            <Text style={{ color: "#0E7490", fontSize: 14, margin: "8px 0 0" }}>{daily.serviceName}</Text>
          </Section>
          <Section style={{ padding: "32px 34px 34px" }}>
            <Text style={{ fontSize: 14, margin: "0 0 18px" }}>Hola / Hello{recipientName ? ` ${recipientName}` : ""},</Text>
            <Text style={{ color: "#475569", fontSize: 14, lineHeight: "22px", margin: "0 0 4px" }}>
              Adjuntamos los dos reportes del servicio correspondientes al {daily.reportDate}: resumen diario y total acumulado.
            </Text>
            <Text style={{ color: "#475569", fontSize: 14, lineHeight: "22px", margin: "0 0 18px" }}>
              Attached are the two service reports for {daily.reportDate}: the daily summary and the full service total.
            </Text>
            <Row>
              <Column style={{ width: "50%", paddingRight: 6 }}>
                <Section style={{ backgroundColor: "#E0F2FE", padding: 14 }}>
                  <Text style={{ color: "#64748B", fontSize: 11, margin: 0 }}>RESUMEN DEL DIA / DAILY SUMMARY</Text>
                  <Text style={{ color: "#0E7490", fontSize: 24, fontWeight: 700, margin: "4px 0" }}>{daily.totalBulbs.toLocaleString("es-CL")}</Text>
                  <Text style={{ color: "#475569", fontSize: 12, margin: 0 }}>bulbos / bulbs - {daily.lotes.length} lotes / lots</Text>
                </Section>
              </Column>
              <Column style={{ width: "50%", paddingLeft: 6 }}>
                <Section style={{ backgroundColor: "#F8FAFC", padding: 14 }}>
                  <Text style={{ color: "#64748B", fontSize: 11, margin: 0 }}>TOTAL DEL SERVICIO / SERVICE TOTAL</Text>
                  <Text style={{ color: "#172033", fontSize: 24, fontWeight: 700, margin: "4px 0" }}>{total.totalBulbs.toLocaleString("es-CL")}</Text>
                  <Text style={{ color: "#475569", fontSize: 12, margin: 0 }}>bulbos / bulbs - {total.lotes.length} lotes / lots</Text>
                </Section>
              </Column>
            </Row>
            <Hr style={{ borderColor: "#E2E8F0", margin: "24px 0" }} />
            <Text style={{ color: "#475569", fontSize: 13, lineHeight: "20px" }}>
              Los PDFs incluyen detalle por lote, calibre, porcentaje, bins y actividad horaria / The PDFs include lot, size, percentage, bin and activity-time details.
            </Text>
            <Text style={{ color: "#94A3B8", fontSize: 11, lineHeight: "18px" }}>
              Mensaje generado automaticamente por QUALIBLICK / Automatically generated by QUALIBLICK.
            </Text>
          </Section>
          <Section style={{ backgroundColor: "#F8FAFC", padding: "22px 34px 26px" }}>
            <Text style={{ color: "#94A3B8", fontSize: 11, margin: 0 }}>QUALIBLICK</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}
