import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Img,
  Preview,
  Section,
  Text,
} from "@react-email/components";
import { strings } from "@/lib/reporting/i18n";
import type { ReportLang, ServiceReport } from "@/lib/reporting/types";

interface ServiceReportEmailProps {
  daily: ServiceReport;
  recipientName?: string | null;
  /** Los entregables salen en ingles; el castellano es solo para revision. */
  lang?: ReportLang;
}

const font = "Arial, Helvetica, sans-serif";

/**
 * El cuerpo es solo una nota de acompanamiento: las cifras van en el PDF y el
 * Excel adjuntos. Duplicarlas aca obligaba a mantener tres vistas del mismo
 * dato y hacia el correo largo sin agregar nada.
 */
export default function ServiceReportEmail({
  daily,
  recipientName,
  lang = "en",
}: ServiceReportEmailProps) {
  const t = strings(lang);

  return (
    <Html>
      <Head />
      <Preview>{`QUALIBLICK ${t.serviceReport} - ${daily.serviceName} - ${daily.reportDate}`}</Preview>
      <Body style={{ backgroundColor: "#F1F5F9", margin: 0, fontFamily: font, color: "#172033" }}>
        <Container style={{ maxWidth: 680, margin: "0 auto", backgroundColor: "#FFFFFF" }}>
          <Section
            style={{
              backgroundColor: "#FFFFFF",
              padding: "30px 34px 22px",
              borderBottom: "5px solid #0E7490",
            }}
          >
            <Img
              src="cid:qualiblick-logo"
              alt="QUALIBLICK"
              width="190"
              style={{ display: "block", height: "auto" }}
            />
            <Text style={{ color: "#0E7490", fontSize: 11, letterSpacing: 2, margin: "14px 0 0" }}>
              {t.reporting}
            </Text>
            <Heading style={{ color: "#172033", fontSize: 25, margin: "8px 0 0" }}>
              {t.serviceReport}
            </Heading>
            <Text style={{ color: "#0E7490", fontSize: 14, margin: "8px 0 0" }}>
              {daily.serviceName}
            </Text>
          </Section>
          <Section style={{ padding: "28px 34px 30px" }}>
            <Text style={{ fontSize: 14, margin: "0 0 14px" }}>
              {t.hello}
              {recipientName ? ` ${recipientName}` : ""},
            </Text>
            <Text
              style={{ color: "#475569", fontSize: 14, lineHeight: "22px", margin: "0 0 20px" }}
            >
              {t.intro(daily.reportDate)}
            </Text>
            <Text style={{ color: "#94A3B8", fontSize: 11, lineHeight: "18px", margin: 0 }}>
              {t.autoGenerated}
            </Text>
          </Section>
          <Section style={{ backgroundColor: "#F8FAFC", padding: "22px 34px 26px" }}>
            <Text style={{ color: "#94A3B8", fontSize: 11, margin: 0 }}>QUALIBLICK</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}
